language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm prune
  - npm install
script:
  - npm test
  - npm run clean
  # ignore result because is failing on purpose
  - npm run cy:run || true
  - npm run verify-failed-json
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
